### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kapilgarg83** [mavenlink/karousel#8]
nginx-deployment: strconv.ParseFloat: parsing "": invalid syntax

getting this error when I run POD. and this for all POD, svc and deployments
please suggest

failed to parse deployTime for deployment karousel: strconv.ParseFloat: parsing "": invalid syntax
2020/02/03 11:35:37 (2)failed to parse deployTime for deployment nginx-deployment: strconv.ParseFloat: parsing "": invalid syntax
2020/02/03 11:35:37 (2)failed to parse deployTime for deployment pod-ttl-operator: strconv.ParseFloat: parsing "": invalid syntax
2020/02/03 11:35:37 (2)failed to parse deployTime for deployment postgres: strconv.ParseFloat: parsing "": invalid syntax

**Comment by diclophis** [comment]
@kapilgarg83 Sorry for the delay, we no longer support this repo, and will not be able to provide further assistance with this problem.
